---
# Replication controller section
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: service-iam-dnbsearcher

spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: service-iam-dnbsearcher
      annotations:
        coi/policy: iam-search
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "vault-init",
            "image": "containers.cisco.com/oneidentity/vault-init:v1.0",
            "imagePullPolicy": "Always",
            "volumeMounts": [
              {
                "name": "vault-token",
                "mountPath": "/var/run/secrets/coi"
              }
            ]
          }
        ]'
    spec:
      containers:
        - name: service-iam-dnbsearcher
          image: containers.cisco.com/oneidentity/service-iam-dnbsearcher:develop-10
          imagePullPolicy: Always
          env:
            - name: VAULT_SERVICE_NAME
              value: "iam-search"
            - name: ACCESS_TOCKEN_ENDPOINT
              value: "https://cloudsso-test.cisco.com"
            - name: ACCESS_TOCKEN_URI
              value: "/as/token.oauth2?grant_type=client_credentials&client_id=crtservice&client_secret=laenprd"
            - name: ACCESS_TOCKEN_ENDPOINT
              value: "https://crdnb-stage.cisco.com"
            - name: ACCESS_TOCKEN_ENDPOINT
              value: "/dnb/search"
          ports:
            - containerPort: 9443
              protocol: TCP
              name: search
          volumeMounts:
            - name: vault-token
              mountPath: "/var/run/secrets/coi"
          resources:
              limits:
                cpu: '2'
                memory: 4Gi
              requests:
                cpu: 200m
                memory: 2Gi
      volumes:
        - name: vault-token
          emptyDir: {}
---